---
# This playbook contains common plays that will be run on all nodes.

- name: Install Required Packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - build-essential
    - git
    - curl
    - wget
    - python-dev
    - libssl-dev
