---
# This playbook contains common plays that will be run on all nodes.

- include: ssh_key.yml

- name: Install Required Packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items: "{{ common_packages + packages }}"
