---
# This playbook deploys your application to Vagrant
# - name: Installs common tools
#   hosts: all
#   sudo: yes
#   roles:
#     - common

# - name: Install & Configure MySQL
#   hosts: all
#   sudo: yes
#   roles:
#     - role: mysql
#       mysql_bind_address: "127.0.0.1" # The address the mysql server binds on
#       mysql_root_password: "secret" # The root password
#       mysql_databases:
#         - name: homestead
#       mysql_users:
#         - name: homestead
#           pass: secret

- name: Install & Configure Postgres
  hosts: all
  sudo: yes
  roles:
    - role: ANXS.postgresql
      postgresql_version: 9.3
      postgresql_databases:
        - name: homestead
      postgresql_users:
        - name: homestead
          pass: secret

# - name: Install & Configure web project(s)
#   hosts: all
#   sudo: yes
#   roles:
#     - project

# - name: Install & Configure nginx with project sites
#   hosts: all
#   sudo: yes
#   roles:
#     - role:
