---
# This playbook deploys your application to Vagrant
- name: Install NodeJS and NPM
  hosts: all
  sudo: yes
  roles:
    - role: JasonGiedymin.nodejs

- name: Install & Configure MySQL
  hosts: all
  sudo: yes
  roles:
    - role: geerlingguy.mysql
      mysql_root_password: ''
      mysql_users:
        - name: homestead
          host: 127.0.0.1
          password: secret

- name: Install & Configure Postgres
  hosts: all
  sudo: yes
  roles:
    - role: ANXS.postgresql
      postgresql_version: 9.3
      postgresql_users:
        - name: homestead
          pass: secret

# - name: Install & Configure web project(s)
#   hosts: all
#   sudo: yes
#   roles:
#     - project

# - name: Install & Configure nginx with project sites
#   hosts: all
#   sudo: yes
#   roles:
#     - role:
