---
# This playbook deploys your application to Vagrant

- name: Install common tools
  hosts: all
  roles:
    - common

- name: Install & Configure MySQL
  hosts: all
  roles:
    - role: geerlingguy.mysql
      mysql_root_password: ''
      mysql_users:
        - name: homestead
          host: "%"
          password: secret
          priv: "*.*:ALL"
      mysql_databases:
        - name: homestead

- name: Install & Configure Postgres
  hosts: all
  roles:
    - role: ANXS.postgresql
      postgresql_version: 9.3
      postgresql_users:
        - name: homestead
          pass: secret
      #     encrypted: no
      # postgresql_user_privileges:
      #   - name: homestead
      #     db: homestead
      #     priv: "ALL"
      # postgresql_databases:
      #   - name: homestead
      # postgresql_listen_addresses:
      #   - "*"

- name: Install Apache and mod_wsgi
  hosts: all
  roles:
    - role: geerlingguy.apache
      apache_create_vhosts: false
    - mod_wsgi

- name: Install & Configure web project(s)
  hosts: all
  roles:
    - django
