---
# This ansible task is using "register with a loop", to find out more information
# regarding "register with a loop" check the following link:
# http://docs.ansible.com/playbooks_loops.html#using-register-with-a-loop

- name: django | facts | check if django project dir is empty
  command: ls
  args:
    chdir: "{{ item.path }}"
  with_items: "{{projects}}"
  register: results
  changed_when: no
