---

- name: create new django projects
  command: "/home/vagrant/.virtualenvs/{{ item.item.name }}/bin/django-admin.py startproject {{ item.item.name }} ."
  args:
    chdir: "{{ item.item.path }}"
  when: item.stdout|length == 0
  with_items: results.results
