---

- name:  django | permission | check owner of .virtualenvs directory
  stat:
    path: "{{django_virtualenv_path}}"
  register: vir_env

- name: django | permission | fix .virtualenvs permissions
  file:
    group: "{{django_user}}"
    owner: "{{django_user}}"
    path: "{{django_virtualenv_path}}"
    recurse: yes
    state: directory
  when: vir_env.stat.pw_name != "{{django_user}}"
