---

- name: check owner of .virtualenvs directory
  stat:
    path: /home/vagrant/.virtualenvs
  register: vir_env

- debug: msg="{{ vir_env }}"

- name: fix .virtualenvs permissions
  file:
    group: vagrant
    owner: vagrant
    path: /home/vagrant/.virtualenvs
    recurse: yes
    state: directory
  when: vir_env.stat.pw_name == "root"
