---

- name: django | virtualenv | create virtualenvs and add django to virtualenvs
  pip:
    name: django
    virtualenv: "{{django_virtualenv_path}}/{{ item.name }}"
    state: present
  with_items: "{{projects}}"
