---

- name: install virtualenv module
  pip:
    name: virtualenv
    state: present

- name: create virtualenvs and add django to virtualenvs
  pip:
    name: django
    virtualenv: "/home/vagrant/.virtualenvs/{{ item.name }}"
    state: present
  with_items: projects
