---

- name: create virtualenvs and add django to virtualenvs
  pip:
    name: "{{ item[0] }}"
    virtualenv: "/home/vagrant/.virtualenvs/{{ item[1].name }}"
    state: present
  with_nested:
    - [ django, ipdb ]
    - projects
